#
# @title Build and Commit
# @since 2018/08/07
# @author fujisawa-shin
#

version: 2
jobs:
  build_and_commit:
    docker:
      - image: circleci/node:12.4-browsers
    working_directory: ~/app
    environment:
      INSTALL_COMMAND: "npm install"
      BUILD_COMMAND: "./node_modules/.bin/tsc"
      DOC_ROOT: "dist"
      BUILD_BRANCHI_POSTFIX: "build"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "46:09:58:e1:9d:bc:73:66:d7:6d:85:75:15:45:71:23"
      - run:
          name: "git config"
          command: |
            git config --global user.email "circleci@example.com"
            git config --global user.name "circleci"
            git config --global push.default simple
      - run:
          name: "setup branch"
          command: |
            git fetch origin
            git checkout $CIRCLE_BRANCH-$BUILD_BRANCHI_POSTFIX
            git merge $CIRCLE_BRANCH --no-ff -m "merge $CIRCLE_BRANCH"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: "npm install"
          command: $INSTALL_COMMAND
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: "build"
          command: $BUILD_COMMAND
      - run:
          name: "git add"
          command: "git add $DOC_ROOT"
      - run:
          name: "git commit"
          command: |
            set +o pipefail
            git commit -m 'build' | true
      - run:
          name: "tagging"
          command: |
            v=`node -e "console.log(JSON.parse(require('fs').readFileSync('package.json','utf8')).version)"`
            git tag v$v || echo "existing tag v$v"
      - run:
          name: "git push"
          command: "git push origin $CIRCLE_BRANCH-$BUILD_BRANCHI_POSTFIX"

  npm_release:
    docker:
      - image: circleci/node:12.4-browsers
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/app/.npmrc
      - run:
          name: Publish package
          command: npm publish      

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_and_commit:
          filters:
            branches:
              only:
                - master
      - npm_release:
          filters:
            tags:
              only: /^v.*/